site_name: 三绝简
theme: 
  name: "material"
  language: 'zh'
  palette:
    primary: 'light green'
    accent: 'deep orange'
  logo:
    icon: 'local_library'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
extra:
  search:
    language: 'ja'